config/urls.py
from pathlib import Path
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('it_english.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('allauth.urls')),
]

it_english/urls.py
from django.urls import path
from django.urls.conf import include

from it_english.views import accountView, questionView, wordEditView, profileView,aboutUsView

app_name = "it_english"

urlpatterns = [
    path('', accountView.index, name='index'),
    path('signup/', accountView.signup, name='signup'),
    path('login/', accountView.account_login, name='login'),
    path('choice/',questionView.choiceTemplateView.as_view(), name='choice'),

    path('word_top/', wordEditView.word_top, name='word_top'),
    path('word_add/', wordEditView.word_add, name='word_add'),
    path('result/',questionView.result,name='result'),
    path('word_edit/', wordEditView.word_edit, name='word_edit'),
    path('q_answer/',questionView.q_answerTemplateView.as_view(),name='q_answer'),
    path('quiz', wordEditView.quiz, name='quiz'),
    path('profile/',profileView.comingsoon,name='comingsoon'),
    path('aboutus/',aboutUsView.authors,name='aboutus'),
]

it_english/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import EmailField

# Create your models here.

class UserModel(models.Model):
  name = models.CharField(max_length= 20)
  email = models.EmailField(max_length=254, unique=True)
  password = models.CharField(max_length=50)
  secret_question = models.CharField(max_length=100)

class AdministratorModel(models.Model):
  name = models.CharField(max_length= 20)
  email = models.EmailField(max_length=254, unique=True)
  password = models.CharField(max_length=50)

class QuizModel(models.Model):
  quiz = models.CharField(max_length= 200)
  op1 = models.CharField(max_length=200)
  op2 = models.CharField(max_length=200)
  op3 = models.CharField(max_length=200)
  op4 = models.CharField(max_length=200)
  answer = models.CharField(max_length= 200)
  administrator_id = models.ForeignKey(AdministratorModel, on_delete=models.CASCADE)

  def __str__(self):
    return self.quiz

class Quiz_levelModel(models.Model):
  level = models.CharField(max_length= 20)

class Quiz_quiz_levelModel(models.Model):
  quiz_level_id = models.ForeignKey(Quiz_levelModel, on_delete=models.CASCADE)
  quiz_id = models.ForeignKey(QuizModel, on_delete=models.CASCADE)

class Answer_historyModel(models.Model):
  user_id = models.ForeignKey(UserModel, on_delete=models.CASCADE)
  selectes_level = models.CharField(max_length = 20)

class Answer_detail_historyModel(models.Model):
  answer_history_id = models.ForeignKey(Answer_historyModel, on_delete=models.CASCADE)
  quiz_id = models.ForeignKey(QuizModel, on_delete=CASCADE)

it_english/forms.py
from it_english.models import QuizModel
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import fields
from django.forms.models import ModelForm


class UserCreateForm(UserCreationForm):
    # email = forms.EmailField(required=True, max_length=100)

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ("username", "password")

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class QuizAddForm(ModelForm):
    class Meta:
        model = QuizModel
        fields = "__all__"

it_english/views/aboutUsView.py
from django.shortcuts import render

def authors(request):
    return render(request, 'aboutUs/authors.html')

it_english/views/accountView.py
from it_english.forms import LoginForm, UserCreateForm
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.http import HttpResponse, response


def index(request):
    if request.user.is_authenticated:
        return redirect("it_english:choice")
    else:
        return redirect("it_english:login")


def signup(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance,backend='django.contrib.auth.backends.ModelBackend')
            return redirect("it_english:choice")
    else:
        form = UserCreateForm()

    context = {
        "form": form
    }
    return render(request, 'signup/signup.html', context)


class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('it_english:choice')
        return render(request, 'registration/login.html', {'form': form, })

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'registration/login.html', {'form': form, })


account_login = Account_login.as_view()

it_english/views/profileView.py
from django.shortcuts import render

def comingsoon(request):
    return render(request, 'profile/comingsoon.html')

it_english/views/questionView.py
from django.contrib.auth import login
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse

class q_answerTemplateView(LoginRequiredMixin,TemplateView):
    template_name = 'question/q_answer.html'
    login_url = '/login/'

class choiceTemplateView(LoginRequiredMixin,TemplateView):
    template_name = "question/choice.html"
    login_url = "/login/"

def result(request):
    return render(request, 'question/result.html')

it_english/views/wordEditView.py
from it_english.forms import QuizAddForm
from it_english.models import QuizModel
from django.shortcuts import render, redirect
from django.http import HttpResponse


def word_top(request):
    lists = QuizModel.objects.all()
    return render(request, 'word/word_top.html',{"lists": lists})

def word_add(request):
    if request.user.is_staff:
        form = QuizAddForm
        if(request.method == 'POST'):
            form = QuizAddForm(request.POST)
            if(form.is_valid()):
                form.save()
                return redirect('quiz/word_add.html')
        context = {
            'form':form
        }
        return render(request, 'quiz/word_add.html',context)
    else:
        return redirect('quiz')

def word_edit(request):
    return render(request, 'quiz/word_edit.html',{})

def quiz(request):
    if request.method == 'POST':
        print(request.POST)
        quizzes = QuizModel.objects.all()
        score = 0
        wrong = 0
        correct = 0
        total = 0
        for q in quizzes:
            total += 1
            print(request.POST.get(q.quiz))
            print(q.answer)
            if q.answer == request.POST.get(q.quiz):
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score / (total * 10) * 100
        context = {
            'score':score,
            'percent':percent,
            'correct':correct,
            'wrong':wrong,
            'total':total,
        }
        return render(request, 'quiz/result.html', context)
    else:
        quizzes = QuizModel.objects.all()
        context = {
            'quizzes':quizzes
        }
        return render(request, 'quiz/quiz.html', context)

it_english/templates/aboutUs/authors.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>it_english</title>
    <style>
        @import url("https://fonts.googleapis.com/css?family=Share+Tech+Mono|Montserrat:700");

* {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
    box-sizing: border-box;
    color: inherit;
}

body {
    background-image: linear-gradient(120deg, #656531 0%, #000000 100%);
    height: 100vh;
}

h1 {
    font-size: 20vw;
    text-align: center;
    position: fixed;
    width: 100vw;
    z-index: 1;
    color: #ffffff26;
    text-shadow: 0 0 50px rgba(0, 0, 0, 0.07);
    top: 50%;
    transform: translateY(-50%);
    font-family: "Montserrat", monospace;
}

div {
    background: rgba(0, 0, 0, 0);
    width: 70vw;
    position: relative;
    top: 50%;
    transform: translateY(-50%);
    margin: 0 auto;
    padding: 30px 30px 10px;
    box-shadow: 0 0 150px -20px rgba(0, 0, 0, 0.5);
    z-index: 3;
}

P {
    font-family: "Share Tech Mono", monospace;
    color: #f5f5f5;
    margin: 0 0 20px;
    font-size: 17px;
    line-height: 1.2;
}

a {
    color: #FFAF25;
}

span {
    color: #;
}

i {
    color: #BCAFFF;
}

k{
    color:#FFAFFF;
}

div a {
    text-decoration: none;
}

b {
    color: #FFCC00;
}

x{
    color: #CBFFD3;
}
a.avatar {
    position: fixed;
    bottom: 15px;
    right: -100px;
    animation: slide 0.5s 4.5s forwards;
    display: block;
    z-index: 4
}

a.avatar img {
    border-radius: 100%;
    width: 44px;
    border: 2px solid white;
}

@keyframes slide {
    from {
        right: -100px;
        transform: rotate(360deg);
        opacity: 0;
    }
    to {
        right: 15px;
        transform: rotate(0deg);
        opacity: 1;
    }
}
    </style>
</head>
<body>
    <h1>About Us</h1>

<div>
<p><span>WHO WE ARE</span></p>
<p>> <a href='https://github.com/shuttleblo'>Shuttle</a>: "<i>I will be a superman!!</i>"</p>
<p>> <a href='https://github.com/daichi0918'>Daichi</a>: "<k>My motto is “continuity is the father of success.</k>"</p>
<p>> <a href='https://github.com/waktia'>Wakita</a>: <b>zenmon toitemiyo huhahahahahahahahahahahahahahahahaha</b>...</p>
<p>> <a href='https://github.com/Rinasham'>Rina</a>: <x>I just want to go back to Japan</x>...</p>
<p>> <span>CLICK OUR NAMES </span>: and you can jump to our GitHub pages</p>
<p>> <span>VISIT THE WEBSITE OF OUR IT SCHOOL! >>>> RARETECH: </span><a href='https://raretech.site/'>https://raretech.site/</a><span> ←Click the URL</span></p>
</div>


<script type="text/javascript">
var str = document.getElementsByTagName('div')[0].innerHTML.toString();
var i = 0;
document.getElementsByTagName('div')[0].innerHTML = "";

setTimeout(function() {
    var se = setInterval(function() {
        i++;
        document.getElementsByTagName('div')[0].innerHTML = str.slice(0, i) + "|";
        if (i == str.length) {
            clearInterval(se);
            document.getElementsByTagName('div')[0].innerHTML = str;
        }
    }, 10);
},0);
</script>
</body>
</html>

it_english/templates/question/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% comment %} <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"> {% endcomment %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        {% comment %} <link href="https://fonts.googleapis.com/css?family=Oswald:700" rel="stylesheet"> {% endcomment %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        <link rel="stylesheet" href="{% static 'css/question/q_answer.css' %}">
        {% block extra_css %} {% endblock %}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@500&display=swap" rel="stylesheet">

        <title>IT English</title>
    </head>
<body>
  <header class="bar1 fixed-top">
    <nav class="navbar navbar-expand-md" >
    <!-- <nav class="navbar navbar-expand-md navbar-dark bg-primary" id="bar"> -->
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item active">
              <a class="nav-link" aria-current="page" href="{% url 'it_english:choice' %}" id="bar-title">IT English</a>
            </li>
<!--             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav3" aria-controls="navbarNav3" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button> -->
          <div class="collapse navbar-collapse" id="navbarNav3">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <!-- メニュー1 -->
                    <a class="nav-link" href="{% url 'it_english:choice' %}" id="Home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <!-- メニュー2 -->
                    <a class="nav-link" href="{% url 'it_english:comingsoon' %}" id="Profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'it_english:aboutus' %}" id="AboutUs">About Us</a>
                </li>
                <li class="nav-item">
                    <!-- メニュー3 -->
                    <a class="nav-link" href="{% url 'logout' %}" id="Logout">Logout</a>
                </li>
            </ul>
            <!-- ハンバーガーメニュー参考サイトhttps://teratail.com/questions/293009 -->
        </div>
            
          </ul>
        </div>
      </div>
    </nav>
    <!-- <nav class="navbar navbar-dark bg-primary">
      <div class="container-fluid"></div>
      <a class="home" href="#">Home</a>
      </div>
    </nav> -->
  </header>
    {% block body %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'js/question/base.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/question/q_answer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/question/result.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/question/choice.js' %}"></script>
</body>
</html>

it_english/templates/question/choice.html
{% extends "question/base.html" %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/question/choice.css' %}">
{% endblock %}


{% block body %}

<main>
    <div class="inner">
        <h1 id="position">問題数を選んでください。</h1>
        <div class="choice">
            <div class="animation">
                <div class="effect"></div>
                    <a href="/q_answer" id="Five"> 5問 </a>
            </div>
            <div class="animation">
                <div class="effect"></div>
                    <a href="/q_answer" id="Ten"> 10問 </a>
            </div>
            <div class="animation">
                <div class="effect"></div>
                    <a href="/q_answer" id="Thirty"> 30問 </a>
            </div>
            <div class="animation">
                <div class="effect"></div>
                    <a href="/q_answer" id="Fifty"> 50問 </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

it_english/templates/question/q_answer.html
{% extends "question/base.html" %}

{% block body %}

<main id="main">
  <div class="container-fluid">
    <h1 style="text-align:center" id="title"></h1>
    <div class="shadow p-2">
      <div class="row">
        <div class="col-lg-12">
          <h1 style="text-align:center" id="js-question">
          </h1>
        </div>
        <div class="col d-flex justify-content-center">
          <input type="button" id="button" onclick="pronounce()" value="発音を確認">
          <script type="text/javascript">
            function pronounce() {
              var utterThis = new SpeechSynthesisUtterance();
              var textContent = quizshuffle[quizIndex].question
              utterThis.text = textContent;
              utterThis.lang = 'en-US'
              speechSynthesis.speak(utterThis);
              }
          </script>
        </div>
      </div>
      <br />
      <br /> 
      <br /> 
      <div class="quiz_area">
        <div class="quiz_area_bg"></div>
        <div class="quiz_area_icon"></div>
      </div>
      <div id="a_select">
        <button type="button" class="btn btn-outline-dark px-4" id="button1" value="" >Primary</button>
        <button type="button" class="btn btn-outline-dark px-4" id="button2" value="" >Primary</button>
        <button type="button" class="btn btn-outline-dark px-4" id="button3" value="" >Primary</button>
        <button type="button" class="btn btn-outline-dark px-4" id="button4" value="" >Primary</button>
      </div>
  
  <!-- <div class="row">
    <div class="col-lg-3 offset-md-10" >
    <button type="submit" class="btn btn-warning" id="submit">Next

    </button>
    <-- <button type="submit" class="btn btn-warning" id="submit">Next
      <i class="fa fa-check" aria-hidden="true"></i>
    </button> -->
    </div>
    <div class='next'>
      <input type="button" class="mt-5" id="Next" value="Next">
    </div>
    <h3 class="mt-5" id="result">
    </h3>
  </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
  crossorigin="anonymous"></script>

{% endblock %}

it_english/templates/question/result.html
{% extends "question/base.html" %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/question/result.css' %}">
{% endblock %}


{% block body %}
<main>
    <div class="inner">
        <h1 id="finish">終了！お疲れ様です</h1>

        <div class="answer">
            <table class="table_correct table-bordered">
                <thead class="thread">
                    <tr><th colspan="2">正解した問題</th></tr>
                </thread>
                <tbody id="tbody_correct">
                </tbody>
            </table>
            <table class="table_incorrect table-bordered">
                <thead class="thread">
                    <tr><th colspan="3">不正解の問題</th></tr>
                </thread>
                <tbody id="tbody_incorrect">
                </tbody>
            </table>
        </div>

        <div class="back">
            <div class="animation">
                <div class="effect"></div>
                    <a href="{% url 'it_english:choice' %}">トップに戻る</a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

it_english/templates/quiz/quiz.html
{% extends "question/base.html" %}

{% block body %}
    <div class="container">
        <h1>IT English</h1>

        <form method="POST" action="{% url 'it_english:quiz' %}">
            {% csrf_token %} 

            {% for q in quizzes %}
                <div class="form-group">
                    <label for="quiz">{{q.quiz}}</label>
                </div>
                <div class="form-check">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{q.quiz}}" id="gridRadios1" value="option1" checked>
                        <label class="form-check-label" for="gridRadios1">
                            {{q.op1}}
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{q.quiz}}" id="gridRadios2" value="option2">
                        <label class="form-check-label" for="gridRadios2">
                            {{q.op2}}
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{q.quiz}}" id="gridRadios1" value="option3">
                        <label class="form-check-label" for="gridRadios1">
                            {{q.op3}}
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{q.quiz}}" id="gridRadios2" value="option4">
                        <label class="form-check-label" for="gridRadios2">
                            {{q.op4}}
                        </label>
                    </div>
                    <br>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

it_english/templates/quiz/result.html
{% extends "question/base.html" %}

{% block body %}
    <div class="container">
        <div class="card-columns" style="padding: 10px; margin: 20px;">
            <div class="card align-center" style="width: 32rem; border:5px black solid">
                <img class="card-img-top" src="http://kmit.in/emagazine/wp-content/uploads/2018/02/karnataka-results.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Score: {{score}}</h5>
     
                    <p class="card-text">Percentage: {{percent}}%</p>
                    <p class="card-text">Correct answers: {{correct}}</p>
                    <p class="card-text">Incorrect answers: {{wrong}}</p>
                    <p class="card-text">Total questions: {{total}}</p>
                    <h5>All the best for next quiz!</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

it_english/templates/quiz/word_add.html
{% extends "question/base.html" %}

{% block body %}
    
    <div class="jumbotron container row">
        <div class="col-md-6">
            <h1>Add Question</h1>
            <div class="card card-body">
               <form action="" method="POST">
                  {% csrf_token %}
                    {{form.as_p}}
                    <br>
                 <input type="submit" name="Submit">
                 </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

it_english/templates/signup/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>it_english</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup/signup.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

it_english/templates/signup/signup.html
{% extends "signup/base.html" %}

{% block body %}
    <div class="container">
        <div class="inner">
            <div class="greeting mt-1">
                <p class="welcome" style="text-align:center">Welcome to</p>
                <p class="itenglish" style="text-align:center">IT English</p>
            </div>

            <div class="input text-center">
                <div class="input-child">
                    <form method="post" action="" class="form-group row justify-content-center">
                        {% csrf_token %}
                        {% for item in form %}
                            <div class="form-group col-sm-8 m-3">
                                <input 
                                    type="{{item.field.widget.input_type}}"
                                    placeholder="{{item.label}}"
                                    class="form-control p-3" 
                                    {% if item.field.required %}required{% endif %} 
                                    name="{{item.name}}" 
                                    id="{{item.id_for_label}}">
                            </div>
                        {% endfor %}
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                        <button type="submit" class="submit btn btn-primary w-50 m-3">Create your account</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
        {% comment %} <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> {% endcomment %}
{% endblock %}

it_english/templates/word/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>it_english</title>
    <script src="https://kit.fontawesome.com/6716af155d.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/word/word.css' %}">

</head>

<header>
    <div>
        {% block header %}
        {% endblock %}
    </div>
    <div class='My_page'>
        <a href='#'>My page</a>
    </div>
    <div class='logout'>
        <a href='#'>logout</a>
    </div>

</header>

<body>
    {% block body %}
    {% endblock %}
</body>
</html>

it_english/templates/word/word_add.html
{% extends "word/base.html" %}
{% load static %}


{% block header %}
<strong class="top_title">問題作成</strong>
{% endblock %}

{% block body %}

<div class="top_reverse">
  <a href="#">単語リストへ戻る<i class="fas fa-undo-alt"></i></a>
    </div>
<div class="edit_container">
<form method="POST" enctype="multipart/form-data">{% csrf_token %}

  <p class="edit_form">英単語</p>
  <input type="text"class="edit_formbox" name="英単語"></p>

  <p class="edit_form">解答</p>
  <input type="text" class="edit_formbox" name="解答"></p>
  <p class="edit_form">選択肢A</p>
  <input type="text" class="edit_formbox" name="選択肢A"></p>
  <p class="edit_form">選択肢B</p>
  <input type="text" class="edit_formbox" name="選択肢B"></p>
  <p class="edit_form">選択肢C</p>
  <input type="text" class="edit_formbox" name="選択肢C"></p>

    <input type="submit" value="新規作成">
  </form>
</div>


{% endblock %}